### ISSUE TITLE
NullReferencePointer

### ISSUE THREAD

**Issue by nqwifly** [LocalJoost/QRCodeService#3]
I tried the code from the 'main' and 'changePackageName' branches on Unity 2019.4.17f1 and faced the same issue. The development console in the scene shows me: NullReferencePointer

Here is the debug log for your reference, the code got detected but nothing then happened on the scene.

```
Found QR code hello
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
MRTKExtensions.QRCodes.QRCodeTrackingService:SendProgressMessage(String)
MRTKExtensions.QRCodes.QRCodeTrackingService:QRCodeWatcher_Updated(Object, QRCodeUpdatedEventArgs)
WinRT.EventSource'3:Invoke(IntPtr, IntPtr)
WinRT.<>c__DisplayClass1_0:<_invoke>b__0(_Invoke)
WinRT.Delegate:MarshalInvoke(IntPtr, Action1)
WinRT.EventSource:_invoke(IntPtr, IntPtr, IntPtr)
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)


Exception thrown at 0x76CF94FB in QRCodeService.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x1585D278.
Exception thrown at 0x76CF94FB in QRCodeService.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x1585F650.
Exception thrown at 0x76CF94FB (KernelBase.dll) in QRCodeService.exe: WinRT originate error - 0x80004003 : 'Invalid pointer'.
Exception thrown at 0x76CF94FB in QRCodeService.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x1585F8C8.
Exception thrown at 0x76CF94FB in QRCodeService.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Microsoft.MixedReality.QR.dll!67861C01: ReturnHr(79) tid(1698) 80004003 Invalid pointer
    Msg:[winrt::hresult_error: Invalid pointer] 
Exception thrown at 0x76CF94FB (KernelBase.dll) in QRCodeService.exe: 0x40080202: WinRT transform error (parameters: 0x80004003, 0x00000000, 0x00000027, 0x1585E790).
```

**Comment by LocalJoost** [comment]
Did you build for Master/Arm64?

Joost van Schaik

Senior Software Architect Mixed Reality
Windows Development MVP & Windows Insider MVP

LinkedIn: https://linkedin.com/in/joostvanschaik
Blog: https://localjoost.github.io
Twitter: https://twitter.com/localjoost

"The world as I envision it in my head is such a more interesting place"
________________________________
From: nqwifly ***@***.***>
Sent: Sunday, March 28, 2021 10:53:46 AM
To: LocalJoost/QRCodeService ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LocalJoost/QRCodeService] NullReferencePointer (#3)


I tried the code from the 'main' and 'changePackageName' branches on Unity 2019.4.17f1 and faced the same issue. The development console in the scene shows me: NullReferencePointer

Here is the debug log for your reference, the code got detected but nothing then happened on the scene.

Found QR code hello UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[]) UnityEngine.Logger:Log(LogType, Object) UnityEngine.Debug:Log(Object) MRTKExtensions.QRCodes.QRCodeTrackingService:SendProgressMessage(String) MRTKExtensions.QRCodes.QRCodeTrackingService:QRCodeWatcher_Updated(Object, QRCodeUpdatedEventArgs) WinRT.EventSource3:Invoke(IntPtr, IntPtr)
WinRT.<>c__DisplayClass1_0:<_invoke>b__0(_Invoke)
WinRT.Delegate:MarshalInvoke(IntPtr, Action`1)
WinRT.EventSource:_invoke(IntPtr, IntPtr, IntPtr)

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)

Exception thrown at 0x76CF94FB in QRCodeService.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x1585D278.
Exception thrown at 0x76CF94FB in QRCodeService.exe: Microsoft C++ exception: Il2CppExceptionWrapper at memory location 0x1585F650.
Exception thrown at 0x76CF94FB (KernelBase.dll) in QRCodeService.exe: WinRT originate error - 0x80004003 : 'Invalid pointer'.
Exception thrown at 0x76CF94FB in QRCodeService.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x1585F8C8.
Exception thrown at 0x76CF94FB in QRCodeService.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Microsoft.MixedReality.QR.dll!67861C01: ReturnHr(79) tid(1698) 80004003 Invalid pointer
Msg:[winrt::hresult_error: Invalid pointer]
Exception thrown at 0x76CF94FB (KernelBase.dll) in QRCodeService.exe: 0x40080202: WinRT transform error (parameters: 0x80004003, 0x00000000, 0x00000027, 0x1585E790).`

**Comment by nqwifly** [comment]
Thank you for the quick response. No, the above output from ARM architecture. 
When I try to build for ARM64 with master I got the following errors:

```
1>------ Build started: Project: Il2CppOutputProject, Configuration: Master ARM64 ------
1>Building GameAssembly.dll with MsvcWinRtToolChain
1>	Msvc Install Version: 15.0
1>	Msvc Install SDK Directory: C:\Program Files (x86)\Windows Kits\10
1>	Msvc Linker Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\ARM64\link.exe
1>	Msvc Compiler Path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\ARM64\cl.exe
1>
1>	Output directory: C:\unity_projects\QRCodeService\app_debug\build\bin\ARM64\Master
1>	Cache directory: C:\unity_projects\QRCodeService\app_debug\build\obj\il2cppOutputProject\ARM64\Master
1>il2cpp.exe didn't catch exception: Unity.IL2CPP.Building.BuilderFailedException: Il2CppMetadataUsage.c
1>EXEC : fatal error C1007: unrecognized flag '-ssa-cfg-jt-' in 'p2'
1>
1>Invocation was: Executable: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\ARM64\cl.exe"
1>Arguments: "C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\Source\il2cppOutput\Il2CppMetadataUsage.c" /nologo /c /bigobj /W3 /Zi /EHs /GR- /Gy /utf-8 /wd4102 /wd4800 /wd4056 /wd4190 /wd4723 /wd4467 /wd4503 /wd4996 /wd4200 /Ox /Oi /Oy- /GS- /Gw /GF /Zo /MD -d2ssa-cfg-jt- /DWINDOWS_UWP /DUNITY_UWP /DUNITY_WSA_10_0 /DUNITY_WSA /DUNITY_WINRT /DPLATFORM_WINRT /DNET_4_0 /DUNITY_AOT /DIL2CPP_MONO_DEBUGGER_DISABLED /DGC_NOT_DLL /DRUNTIME_IL2CPP /DIL2CPP_DEFAULT_DATA_DIR_PATH=Data/il2cpp_data /D_WIN32 /DWIN32 /DWIN32_THREADS /D_WINDOWS /DWINDOWS /D_UNICODE /DUNICODE /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS /D_WINSOCK_DEPRECATED_NO_WARNINGS /DNOMINMAX /D_NDEBUG /DNDEBUG /DWINDOWS_SDK_BUILD_VERSION=18362 /D__WRL_NO_DEFAULT_LIB__ /DWINAPI_FAMILY=WINAPI_FAMILY_APP /I"C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\IL2CPP\libil2cpp" /I"C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\IL2CPP\libil2cpp" /I"C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\IL2CPP\external\bdwgc\include" /I"C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\IL2CPP\external\xxHash" /I"C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\Source" /I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" /Fo"C:\unity_projects\QRCodeService\app_debug\build\obj\il2cppOutputProject\ARM64\Master\347BD17CAC7822BEB913E2917797DABF.obj" /Fd"C:\unity_projects\QRCodeService\app_debug\build\obj\il2cppOutputProject\ARM64\Master\347BD17CAC7822BEB913E2917797DABF.pdb"
1>EnvArg key: PATH value: C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64
1>
1>   at Unity.IL2CPP.Building.CppProgramBuilder.BuildAllCppFiles(IEnumerable`1 sourceFilesToCompile, IBuildStatisticsCollector statisticsCollector)
1>   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
1>   at il2cpp.Program.DoRun(String[] args, List`1 foundAssemblies)
1>   at il2cpp.Program.Run(String[] args, Boolean setInvariantCulture)
1>   at il2cpp.Program.Main(String[] args)
1>
1>Unhandled Exception: Unity.IL2CPP.Building.BuilderFailedException: Il2CppMetadataUsage.c
1>EXEC : fatal error C1007: unrecognized flag '-ssa-cfg-jt-' in 'p2'
1>
1>Invocation was: Executable: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\ARM64\cl.exe"
1>Arguments: "C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\Source\il2cppOutput\Il2CppMetadataUsage.c" /nologo /c /bigobj /W3 /Zi /EHs /GR- /Gy /utf-8 /wd4102 /wd4800 /wd4056 /wd4190 /wd4723 /wd4467 /wd4503 /wd4996 /wd4200 /Ox /Oi /Oy- /GS- /Gw /GF /Zo /MD -d2ssa-cfg-jt- /DWINDOWS_UWP /DUNITY_UWP /DUNITY_WSA_10_0 /DUNITY_WSA /DUNITY_WINRT /DPLATFORM_WINRT /DNET_4_0 /DUNITY_AOT /DIL2CPP_MONO_DEBUGGER_DISABLED /DGC_NOT_DLL /DRUNTIME_IL2CPP /DIL2CPP_DEFAULT_DATA_DIR_PATH=Data/il2cpp_data /D_WIN32 /DWIN32 /DWIN32_THREADS /D_WINDOWS /DWINDOWS /D_UNICODE /DUNICODE /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS /D_WINSOCK_DEPRECATED_NO_WARNINGS /DNOMINMAX /D_NDEBUG /DNDEBUG /DWINDOWS_SDK_BUILD_VERSION=18362 /D__WRL_NO_DEFAULT_LIB__ /DWINAPI_FAMILY=WINAPI_FAMILY_APP /I"C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\IL2CPP\libil2cpp" /I"C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\IL2CPP\libil2cpp" /I"C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\IL2CPP\external\bdwgc\include" /I"C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\IL2CPP\external\xxHash" /I"C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\Source" /I"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt" /I"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt" /Fo"C:\unity_projects\QRCodeService\app_debug\build\obj\il2cppOutputProject\ARM64\Master\347BD17CAC7822BEB913E2917797DABF.obj" /Fd"C:\unity_projects\QRCodeService\app_debug\build\obj\il2cppOutputProject\ARM64\Master\347BD17CAC7822BEB913E2917797DABF.pdb"
1>EnvArg key: PATH value: C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64
1>
1>   at Unity.IL2CPP.Building.CppProgramBuilder.BuildAllCppFiles(IEnumerable`1 sourceFilesToCompile, IBuildStatisticsCollector statisticsCollector)
1>   at Unity.IL2CPP.Building.CppProgramBuilder.Build(IBuildStatistics& statistics)
1>   at il2cpp.Program.DoRun(String[] args, List`1 foundAssemblies)
1>   at il2cpp.Program.Run(String[] args, Boolean setInvariantCulture)
1>   at il2cpp.Program.Main(String[] args)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command ""C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\\IL2CPP\build\deploy\net471\il2cpp.exe" --libil2cpp-static --compile-cpp -architecture=ARM64 -configuration=Release -platform=winrt -outputpath="C:\unity_projects\QRCodeService\app_debug\\build\bin\ARM64\Master\GameAssembly.dll" --data-folder="C:\unity_projects\QRCodeService\app_debug\\build\bin\ARM64\Master\\" -cachedirectory="C:\unity_projects\QRCodeService\app_debug\\build\obj\il2cppOutputProject\ARM64\Master\\" -generatedcppdir="C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\\Source"  --profiler-report --additional-defines=WINDOWS_UWP --additional-defines=UNITY_UWP --additional-defines=UNITY_WSA_10_0 --additional-defines=UNITY_WSA --additional-defines=UNITY_WINRT --additional-defines=PLATFORM_WINRT -dotnetprofile=unityaot -verbose --relative-data-path=Data/il2cpp_data --map-file-parser="C:\unity_projects\QRCodeService\app_debug\Il2CppOutputProject\\IL2CPP\MapFileParser\MapFileParser.exe" --compiler-flags="-d2ssa-cfg-jt-"" exited with code -532462766.
1>Done building project "Il2CppOutputProject.vcxproj" -- FAILED.
2>------ Build started: Project: QRCodeService, Configuration: Master ARM64 ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): error MSB3273: Unknown processor architecture. The implementation file "C:\Program Files\Unity\Hub\Editor\2019.4.17f1\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\il2cpp\ARM64\Master\UnityPlayer.dll" for "C:\Program Files\Unity\Hub\Editor\2019.4.17f1\Editor\Data\PlaybackEngines\MetroSupport\Players\UAP\il2cpp\ARM64\Master\UnityPlayer.winmd" had an ImageFileMachine value of "0xAA64". If you wish to use this implementation file make sure the "ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch" property in your project is set to "Warning" or "None".
2>Done building project "QRCodeService.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by LocalJoost** [comment]
Would you be so kind not to post reams and reams of stack traces? That really doesn't help.

I suggest you first delete the C++ app generated by Unity. Then build it afresh. Then deploy using VS2019 Arm64/Master. I can't really see what you have installed or configured on your machine.

Of I pull any branch of this app, build and deploy it, it works right away.

Joost van Schaik

Senior Software Architect Mixed Reality
Windows Development MVP & Windows Insider MVP

LinkedIn: https://linkedin.com/in/joostvanschaik
Blog: https://localjoost.github.io
Twitter: https://twitter.com/localjoost

"The world as I envision it in my head is such a more interesting place"
________________________________

**Comment by LocalJoost** [comment]
Okay. I have added building instructions to [my blog post about this ](https://localjoost.github.io/Positioning-QR-codes-in-space-with-HoloLens-2-building-a-'poor-man's-Vuforia'/). I have noticed people trying to build this with random versions of Unity, platform settings and Visual Studio versions. If I build and deploy the app as describes, it works. It _always_ works.

**Comment by nqwifly** [comment]
Thanks a lot Joost, and apologies for any inconvenient content I've posted.

As I upgraded to VS 2019 it works perfectly now.

**Comment by LocalJoost** [comment]
No worries. You have pushed me to update the blog post with all info necessary to build the app successfully ;)
